server:
  port: 8080
  servlet:
    context-path:

spring:
  datasource:
    url: jdbc:mysql://172.16.5.32:3307/ksbc_sys?serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: root001
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    database: 0
    host: 172.16.5.32
    port: 6379
    timeout: 3600
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  session:
    store-type: redis
  application:
    name: ksbc-sso
  dubbo:
    consumer:
      timeout: 10000
    registry:
      address: zookeeper://172.16.5.32:2181
    protocol:
      name: dubbo
      port: 20881

logging:
  level:
    com.cetcxl.ksbc.sso.dao: debug

mybatis:
  type-aliases-package: com.cetcxl.ksbc.sso.model
  mapper-locations: classpath:mapper/*.xml,classpath:mapper/base/*.xml

ldap:
  url: ldap://172.16.10.2:389/
  basedn: dc=cetcxl,dc=com
  domain-name-start: mail=
  domain-name-end: "@cetcxl.com,ou=Users,domainName=cetcxl.com,o=domains,dc=cetcxl,dc=com"

ksbc:
  first-page: /index