server:
  port: 8080
  servlet:
    context-path:
     # hehe
spring:
  datasource:
    url: jdbc:mysql://172.16.5.32:3307/ksbc_sys?serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: root001
    driver-class-name: com.mysql.cj.jdbc.Driver
  elasticsearch:
     rest:
       uris: ["http://172.16.5.32:9200","http://172.16.5.32:9202","http://172.16.5.32:9203"]

  redis:
    database: 0
    host: 172.16.5.32
    port: 6379
    timeout: 3600
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
