server:
  port: 8080
  servlet:
    context-path:

spring:
  redis:
    database: 0
    host: 172.16.5.32
    port: 6379
    timeout: 3600
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  application:
    name: ksbc-management
  dubbo:
    consumer:
      timeout: 10000
    registry:
      address: zookeeper://172.16.5.32:2181
  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    user:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      initialize: true #指定初始化数据源，是否用data.sql来初始化，默认: true
      name: user
      url: jdbc:mysql://172.16.5.32:3307/ksbc_sys?serverTimezone=GMT%2B8&allowMultiQueries=true
      username: root
      password: root001
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: false
      maxPoolPreparedStatementPerConnectionSize: 200

    file:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      initialize: true
      name: file
      url: jdbc:mysql://172.16.5.32:3309/ksbc_ks?serverTimezone=GMT%2B8&allowMultiQueries=true
      username: root
      password: root001
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: false
      maxPoolPreparedStatementPerConnectionSize: 200

    integral:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      initialize: true
      name: integral
      url: jdbc:mysql://172.16.5.32:3310/ksbc_score?serverTimezone=GMT%2B8
      username: root
      password: root001
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: false
      maxPoolPreparedStatementPerConnectionSize: 200
mybatis:
  type-aliases-package: com.cetcxl.ksbc.management.model
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.cetcxl.ksbc.management.dao.fileDao: debug
    com.cetcxl.ksbc.management.dao.integralDao: debug
    com.cetcxl.ksbc.management.dao.userDao: debug


rule:
  ruleId_001: ksbc_rule_001
  ruleId_002: ksbc_rule_002
  ruleId_003: ksbc_rule_003
  ruleId_004: ksbc_rule_004
  ruleId_005: ksbc_rule_005
  ruleId_006: ksbc_rule_006
  ruleId_007: ksbc_rule_007
  name_001: 注册初始化
  name_002: 每日首次登录
  name_003: 上传文档
  name_004: 评论文档
  name_005: 文档前三条评论
  name_006: 举报成功
  name_007: 被举报成功


