server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: notice-manager
  dubbo:
    consumer:
      timeout: 100000
    registry:
      address: zookeeper://172.16.5.32:2181
  datasource:
    url: jdbc:mysql://172.16.5.32:3308/ksbc_notice?serverTimezone=GMT%2B8
    username: root
    password: root001
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    #数据库索引
    database: 0
    host: 172.16.5.32
    port: 6379
    password:
    jedis:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
        #连接超时时间
        timeout: 10000

mybatis:
  type-aliases-package: com.cetcxl.ksbc.notice.dto
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.cetcxl.ksbc.notice: debug
###producer
#该应用是否启用生产者
rocketmq.producer.isOnOff: on
#发送同一类消息的设置为同一个group，保证唯一,默认不需要设置，rocketmq会使用ip@pid(pid代表jvm名字)作为唯一标示
rocketmq.producer.groupName: ${spring.application.name}
#mq的nameserver地址
rocketmq.producer.namesrvAddr: 172.16.5.32:9876
#消息最大长度 默认1024*4(4M)
rocketmq.producer.maxMessageSize: 4096
#发送消息超时时间,默认3000
rocketmq.producer.sendMsgTimeout: 3000
#发送消息失败重试次数，默认2
rocketmq.producer.retryTimesWhenSendFailed: 2

###consumer
##该应用是否启用消费者
rocketmq.consumer.isOnOff: on
rocketmq.consumer.groupName: ${spring.application.name}
#mq的nameserver地址
rocketmq.consumer.namesrvAddr: 172.16.5.32:9876
#该消费者订阅的主题和tags("*"号表示订阅该主题下所有的tags),格式：topic~tag1||tag2||tag3;topic2~*;
rocketmq.consumer.topics: KS_TOPIC~*;KS_SCORE_TOPIC~*;
rocketmq.consumer.consumeThreadMin: 20
rocketmq.consumer.consumeThreadMax: 64
#设置一次消费消息的条数，默认为1条
rocketmq.consumer.consumeMessageBatchMaxSize: 1
