server:
  port: 8080
  servlet:
     context-path:

spring:
  application:
    name: ksbc-ks
  data:
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: 172.16.5.32:9300,172.16.5.32:9302,172.16.5.32:9303
    repositories:
      enabled: true
  elasticsearch:
     rest:
       uris: ["http://172.16.5.32:9200","http://172.16.5.32:9202","http://172.16.5.32:9203"]
  dubbo:
    consumer:
      timeout: 100000
    registry:
      address: zookeeper://172.16.5.32:2181
  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://172.16.5.32:3309/ksbc_ks?serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: root001
    driver-class-name: com.mysql.cj.jdbc.Driver

  # 配置redis
  redis:
    #数据库索引
    database: 0
    host: 172.16.5.32
    port: 6379
    password:
    jedis:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
        #连接超时时间
        timeout: 10000

mybatis:
  type-aliases-package: com.cetcxl.ksbc.ks.model
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.cetcxl.ksbc.ks.dao: debug

alpha:
  cluster:
    address: 172.16.5.32:8080

application:
  #智能合约chaincode
  readAddress: luna
  chainQueryIp: http://172.16.5.27/cc_manager/fabric/invoke
  chainCodeName: zsgx
  appKey: 1aab1a7fe91f4e8f84c8be7f135203d8
  appSecret: c36f56665de4414a88569c4b67204aee
es:
  path: /es_luxicon.txt