server:
  port: 8080
  servlet:
    context-path:
spring:
  redis:
    database: 0
    host: 172.16.5.32
    port: 6379
    timeout: 3600
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  application:
    name: ksbc-score
  dubbo:
    consumer:
      timeout: 100000
    registry:
      address: zookeeper://172.16.5.32:2181
    protocol:
      name: dubbo
      port: 28888
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    base:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      initialize: true #指定初始化数据源，是否用data.sql来初始化，默认: true
      name: base
      url: jdbc:mysql://172.16.5.32:3310/ksbc_score?serverTimezone=GMT%2B8
      username: root
      password: root001
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: false
      maxPoolPreparedStatementPerConnectionSize: 200
  thymeleaf:
      cache: false

logging:
  level:
    com.cetcxl.ksbc.score.dao: debug


mybatis:
  type-aliases-package: com.cetcxl.ksbc.score.model
  mapper-locations: classpath:mapper/*.xml